# Generated by Django 6.0.3 on 2026-03-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_inquiry_case_client_notes_case_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('GST', 'GST Services'), ('TAX', 'Income Tax'), ('LEGAL', 'Legal Documentation'), ('NOTARY', 'Notary & Affidavit')], max_length=50)),
                ('sub_service', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='cases.userprofile')),
            ],
        ),
    ]
