# Generated by Django 6.0.3 on 2026-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Manually enter amount before marking as Fulfilled', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'New Request Received'), ('APPROVED', 'Approved by Admin'), ('IN_PROGRESS', 'Work Undergoing'), ('VERIFICATION', 'Document Verification'), ('FULFILLED', 'Service Completed'), ('REJECTED', 'Rejected/Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
