# Generated by Django 6.0.3 on 2026-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_servicerequest_amount_servicerequest_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='razorpay_order_id',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter amount before marking as Fulfilled', max_digits=10),
        ),
    ]
