# Generated by Django 5.0.4 on 2026-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_servicerequest_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(choices=[('TAX', 'Taxation (GST / Income Tax)'), ('LICENSE', 'Contractor License / E-Tenders'), ('CRIMINAL', 'Criminal Law / Litigation'), ('NOTARY', 'Notary / Legal Drafting'), ('GENERAL', 'General Inquiry')], default='GENERAL', max_length=100),
        ),
    ]
